<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get Iot Antenna List</name>
   <tag></tag>
   <elementGuidId>547f30da-218b-48d3-8c9f-b5a2d4eae596</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>2b1e568f-884f-4640-bbc4-7e89f1bb8804</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.5.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${baseUrl}/v2/iot/antenna?tag=&lt;string>&amp;scanStatus=&lt;string>&amp;scanStatus=&lt;string>&amp;isActive=&lt;boolean>&amp;isActive=&lt;boolean>&amp;iotReaderId=&lt;string>&amp;reportedDate=&lt;number>&amp;reportedDate=&lt;number>&amp;manager=&lt;string>&amp;manager=&lt;string>&amp;status=&lt;string>&amp;status=&lt;string>&amp;model=&lt;number>&amp;model=&lt;number>&amp;brand=&lt;number>&amp;brand=&lt;number>&amp;group=&lt;number>&amp;group=&lt;number>&amp;antenna=&lt;number>&amp;antenna=&lt;number>&amp;deviceName=&lt;number>&amp;deviceName=&lt;number>&amp;sortOrder=&lt;number>&amp;sortBy=&lt;string>&amp;limit=&lt;number>&amp;page=&lt;number>&amp;search=&lt;string></restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.baseUrl</defaultValue>
      <description></description>
      <id>852895f4-ab78-44b4-9472-7185ee03ad8e</id>
      <masked>false</masked>
      <name>baseUrl</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
